let Define = module.exports = {}

Define.ResultCode = {
	HS_CODE_OK:200,
	HS_CODE_UNKOWN_ERROR:500,
	HS_CODE_INVALID_VERSION:501,
	HS_CODE_UNMATCH_MD5:502,
	HS_CODE_INVALID_RSA:503,
	HS_CODE_UNMATCH_DT_MD5:504
}

Define.ClientState = {
	CS_INITED : 1,
	CS_CONNECTING : 2,
	CS_CONNECTED : 3,
	CS_WORKING : 4,
	CS_DISCONNECTING : 5,
	CS_CLOSED : 6
}